# Site settings
name: Apoorv Dayal
title: Apoorv Dayal | Security Engineer
description: Protect systems from risks, threats and breaches. 
url: https://apoorvdayal.github.io/
baseurl: ''
email: apoorvdayal@jhu.edu
cover: https://apoorvdayal.github.io/img/og.png
logo: https://apoorvdayal.github.io/img/emojis/technologist.png
resume: https://apoorvdayal.github.io/resume.pdf
social:
  - title: email
    url: mailto:apoorvdayal@jhu.edu
  - title: twitter
    url: https://twitter.com/Apoorv13
  - title: instagram
    url: https://instagram.com/apoorv_dayal
  - title: HacktheBox
    url: http://codepen.io/dayAl
  - title: github
    url: https://github.com/Apoorv13
  - title: linkedin
    url: https://www.linkedin.com/in/apoorvdayal

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
